### ISSUE TITLE
Question about calibration

### ISSUE THREAD

**Issue by xiyuanzh** [ZikangLeng/IMUGPT#1]
Hi, thanks for your great work on IMUGPT! 

Upon reading the paper, I have a question about the calibration process which maps the distribution of virtual data to real data. For this calibration, are you calibrating the distribution separately for each class label, or are you calibrating the distribution for the entire dataset altogether?

Look forward to your response!

**Comment by ZikangLeng** [comment]
Hi, thanks for your interest in our work! 

The calibration is done separately for each class label. We did this following the supervised calibration protocol done in IMUTube. See section 5.4.1 of [Approaching the Real-World: Supporting Activity Recognition Training with Virtual IMU Data](https://dl.acm.org/doi/pdf/10.1145/3478096) for more details.

**Comment by xiyuanzh** [comment]
Hi, thanks for your response! Since the calibration is done per class, we need to assume the availability of few-shot labeled samples for the real-world data. In this case, have you compared the performance of random forest classifier/DeepConvLSTM when they are directly trained on these few-shot real samples vs trained on calibrated virtual data? Thanks!

**Comment by ZikangLeng** [comment]
Hi, we have not experimented with training directly using the few-shot real IMU data used for calibration vs calibrated virtual IMU data , we agree that it is worth experimenting in the future. We have experimented with using just a few minutes of real IMU data per class for training, and we find that the model performance is significantly worse when compared to when the model is trianed using the virtual IMU data. This might be similar to what you are looking for. For more information, please refer to figure 2 of [Generating Virtual On-body Accelerometer Data from Virtual Textual Descriptions for Human Activity Recognition](https://dl.acm.org/doi/pdf/10.1145/3594738.3611361)

**Comment by xiyuanzh** [comment]
Got it! Thanks for your detailed response!
