### ISSUE TITLE
Issue of missing dats in the calibrate notebook

### ISSUE THREAD

**Issue by abdelwahed** [ZikangLeng/IMUGPT#2]
Hi ,

Nice work in your paper and thanks for releasing the code. I observed that the calibrate notebook can’t run. The code block below from  calibrate.ipynb is referencing a missing real dataset.  What is the correct path? 

```python
data_dir = 'data/usc-had_50'
ik_mode = '_ik'
noise_mode = ''

for loc in locations:

    Xy_real = pk.load(open(f"{data_dir}/real_{loc}.p",'rb'))
    X_real = Xy_real[0]
    y_real = Xy_real[1]
    for i in range(len(X_real)):
        X_real[i] = np.array(X_real[i])
        y_real[i] = np.array(y_real[i]) 
```

**Comment by ZikangLeng** [comment]
Hi, we do not provide the real IMU data used for calibration. You can calibrate the virtual IMU data using your own virtual IMU data, either collected or from existing datasets. X_real is a list of numpy arrays with shape (num_samples, num_channels), where num_channels is the number of sensor channel. y_real is a list of numpy arrays with shape (num_samples,).

**Comment by abdelwahed** [comment]
No worries and I assume that you flattened the data from  (num_action_samples, num_samples, channels)  into (num_action_samples*num_samples, channels) right ? 

num_action_samples : how many times an action (e.g walking ) was repeated
num_samples : 40 samples if the action was performed for 2 seconds with 20hz sampling rate

**Comment by ZikangLeng** [comment]
That's correct

**Comment by JackLo111** [comment]
Thanks for providing the code! Sorry to bother you that when I tried to gdown the the extractors provided by [t2m](https://github.com/EricGuo5513/text-to-motion), I find my google account doesn't have the authority to visit this google driver. Shall I fill in some form to aquire something?
