### ISSUE TITLE
I can't gdown from the link you provided in download_extractor.sh

### ISSUE THREAD

**Issue by JackLo111** [ZikangLeng/IMUGPT#3]
Thanks for providing the code! Sorry to bother you that when I tried to gdown the the extractors provided by [t2m](https://github.com/EricGuo5513/text-to-motion), I find my google account doesn't have the authority to visit this google driver. Shall I fill in some form to aquire something?

**Comment by Yefancy** [comment]
same issue

**Comment by Yefancy** [comment]
[Checkpoints](https://github.com/EricGuo5513/text-to-motion/commit/c3e241c882b57c2126729ebbab673def410c908f#diff-9a0b293c03456872a596b6e06fbaa68c1b160b0dd703b4b962409979e2087681R26)
it seems that they provide the checkpoints here. haven't tried yet.

**Comment by Yefancy** [comment]
> [Checkpoints](https://github.com/EricGuo5513/text-to-motion/commit/c3e241c882b57c2126729ebbab673def410c908f#diff-9a0b293c03456872a596b6e06fbaa68c1b160b0dd703b4b962409979e2087681R26) it seems that they provide the checkpoints here. haven't tried yet.

it doesnt include the VQVAE.
I found another source from the [`MotionGPT`](https://github.com/OpenMotionLab/MotionGPT/blob/main/prepare/download_t2m_evaluators.sh)

**Comment by ZikangLeng** [comment]
It appears that the google drive link provided by t2m is no longer valid. I have now updated the code to use the extractor provided by [MotionGPT](https://github.com/OpenMotionLab/MotionGPT/blob/main/prepare/download_t2m_evaluators.sh) that @Yefancy found. I have double checked the files, and they are identical to the ones provided by t2m, so everything should be fine. 

The files that you will use are 
`t2m/t2m/t2m/VQVAEV3_CB1024_CMT_H1024_NRES3/meta/mean.npy`
`t2m/t2m/t2m/VQVAEV3_CB1024_CMT_H1024_NRES3/meta/std.npy`

This is also reflected in the updated code.
